baseURL = "https://yeganehazmi.com"
title = "Yeganeh Azmi"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[markup]
  [markup.highlight]
  noClasses = false

  [markup.goldmark.renderer]
  unsafe = true

[params]
author = "Yeganeh Azmi"
description = "Curious and creative Digital Marketer | Social Media, SEO, Content & Analytics"
keywords = "digital marketing, seo, content creation, social media, personal site"
info = ["Digital Marketing Specialist", "Content Creator"]
avatarURL = "images/portrait.png"
dateFormat = "January 2, 2006"
since = 2023
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/yeganehazmi/"

[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
weight = 2
url = "https://www.instagram.com/yeganehazmi"

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 3
url = "https://www.youtube.com/@yeganehazmi"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 4
url = "mailto:yeganehazmi@gmail.com"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[languages.de]
languageName = ":de:"
title = "Yeganeh Azmi"

[languages.de.params]
author = "Yeganeh Azmi"
info = "Junior Digital Marketer in Berlin"
description = "Persönliche Website von Yeganeh Azmi"
keywords = "digital marketing, content, Berlin, SEO, Social Media"

[[languages.de.menu.main]]
name = "Über mich"
weight = 1
url = "about/"

[[languages.de.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.de.menu.main]]
name = "Projekte"
weight = 3
url = "projects/"

[[languages.de.menu.main]]
name = "Kontakt"
weight = 5
url = "contact/"